### PR TITLE
Fixed minor bug with formatting log message

### PR DESCRIPTION
**Pull request by andyone**

### CODE REVIEW

**Comment by logrusorgru** [comment]
Also, `go vet` can help to find typos like this.

**Comment by DisposaBoy** [comment]
@andyone Please submit changes inside `src/margo.sh/` upstream https://github.com/KurokuLabs/margo

I will fix this one along with adding the `go list` support for earlier versions of Go.

**Comment by andyone** [comment]
[Done](https://github.com/KurokuLabs/margo/pull/77)

**Comment by andyone** [comment]
@logrusorgru Cool! Didn't know about this feature.

But I'm not sure how to use it. For example, the command from your example doesn't work:
```
› margo.sh git:(master) grep 'mx.Log.Printf' golang/margocode.go                                                                                                         
                mx.Log.Printf("cannot load the list of stdlib packages", err)

› margo.sh git:(master) go vet -printfuncs=Print,Printf,Println,Fprint,Fprintf,Fprintln,Sprint,Sprintf,Sprintln,Error,Errorf,Fatal,Fatalf,Panic,Panicf,Panicln && echo $?
0
```

**Comment by logrusorgru** [comment]
@andyone , may be

```
go vet -blah=blah ./...
```
For recursive `vet`

**Comment by andyone** [comment]
@logrusorgru Yeah, you are right. Thanks for the explanation.

**Pull request closed without merging**
