### PR TITLE
Use .goignore to make import_paths fast again

### PR DESCRIPTION
**Pull request by maraino**
MarGo import_paths is very slow on large repositories, specially if the `$GOPATH/src` has other projects not written in Go. In my case a bunch of node.js projects with thousands of node_modules directories.

Some projects like https://github.com/maraino/goofimports and others before this one uses a file to avoid going into directories that are not relevant (`$GOPATH/.goignore`)

This PR makes uses of the same file that goofimports (and https://github.com/eugeii/goimports) to know which directories it should ignore.

In my environment the current import_paths takes +50s while the patched one around 1s

### CODE REVIEW

**Comment by DisposaBoy** [comment]
I'd rather fix the issue than hacking around it.

How can I reproduce this? I installed a few node modules and duplicated them until I got 5000+ top-level modules with 22338 directories and 244672 files in total. After the second invocation of the imports list it takes about 1 second as a result of the pkg info cache and disk/dir/stat cache.

**Comment by maraino** [comment]
In my case I have 179242 directories, 151918 if you don't count the ones inside a hidden directory (ie .../.git/....) and a total of 763137 files

**Comment by maraino** [comment]
@DisposaBoy: on large repositories, the use of the ignore fails makes a huge difference, compare here the time that it takes goofimports (with .goignore) vs last version of goimports.

```
mariano@mariano-work:src (master)$ time goofimports -l gosubli.me/margo
gosubli.me/margo/m_gocode.go
gosubli.me/margo/m_lint.go

real	0m0.590s
user	0m1.152s
sys	0m0.394s
mariano@mariano-work:src (master)$ time goimports -l gosubli.me/margo
gosubli.me/margo/m_gocode.go
gosubli.me/margo/m_lint.go

real	0m40.271s
user	0m20.375s
sys	0m43.184s
```

**Comment by DisposaBoy** [comment]
@maraino I'm trying to understand where it's slow and whether or not the caching works. After you load the imports the first time, they're cached, so the only time should be going to `Readdirnames` and `Lstat` which aren't cached. They will be cached eventually but there's no point working on that yet if it's not going to help. If only `node_modules` is the issue, then it's better to just add `strings.Contains(nm, "node_modules") ||` to the list of conditionals in `ignoreNames`... the same way `testdata` is ignored. You can rebuild MarGo by pressing <kbd>ctrl+9</kbd> to open 9o and then running the `margo-reinstall` command.

You can see how long the call takes by enter the following in the Sublime Text console

`imp = lambda *a, **_: len(a) == 2 and isinstance(a[1], str) and 'import_paths' in a[1] and 'response:' in a[1] and print(a[1]); from gosubl import ev; ev.debug += imp`

That will print info about the request in the console. You can disable it with `ev.debug -= imp`

**Comment by maraino** [comment]
@DisposaBoy: here are the results, I've run the import_paths (cmd+.+p) two times:
* Original:
```
>>> imp = lambda *a, **_: len(a) == 2 and isinstance(a[1], str) and 'import_paths' in a[1] and 'response:' in a[1] and print(a[1]); from gosubl import ev; ev.debug += imp
margo response: {'tag': 'r16.05.03-2', 'token': 'mg9.autoken.5ea76766-19f0-462a-b063-14f43e457b2b', 'method': 'import_paths', 'dur': '76.825s', 'size': '62.0K', 'err': ''}
margo response: {'tag': 'r16.05.03-2', 'token': 'mg9.autoken.1f43fde1-8426-44ba-bd1e-7f1e90d7eb26', 'method': 'import_paths', 'dur': '43.106s', 'size': '62.0K', 'err': ''}
```
* Patched:
```
>>> imp = lambda *a, **_: len(a) == 2 and isinstance(a[1], str) and 'import_paths' in a[1] and 'response:' in a[1] and print(a[1]); from gosubl import ev; ev.debug += imp
margo response: {'token': 'mg9.autoken.e1a541f6-c247-4b7d-a388-49a006b0fa08', 'dur': '1.233s', 'tag': 'r16.05.03-2', 'method': 'import_paths', 'size': '61.9K', 'err': ''}
margo response: {'token': 'mg9.autoken.457329c3-a3d2-4111-8104-59b92c9c24c8', 'dur': '0.244s', 'tag': 'r16.05.03-2', 'method': 'import_paths', 'size': '61.9K', 'err': ''}
```
We can add node_modules in ignoreNames, this might solve the issue in my environment, but others might be using python with virtual environments or any other set up.

We can also add this as a GoSublime functionality, allowing to set a file with paths to ignore, so every use can set up this if he wants.

**Comment by maraino** [comment]
@DisposaBoy: instead of this hacky way, this weekend I will try to improve the patch making use of a configuration parameter that you can set the path of the file with the directories to omit. 
Would that be accepted ? 

I've never touch any sublime text plugin before, so I did it the faster way I could to continue using GoSublime, by the way, this was not a problem with previous versions, and my environment didn't change. I've also checked this with some other people with a similar environment and the behavior was the same with the last update. I'll look also in the cache to see if there's a problem with that and figure out why the second time is also slow.

**Comment by DisposaBoy** [comment]
I'm not too sure about adding more configuration as there's far to many there already and when you add a configuration that takes care of the imports, the next question is: what about general package browsing (<kbd>ctrl+.</kbd>,<kbd>ctrl+a</kbd>) or file browsing (<kbd>ctrl+.</kbd>,<kbd>ctrl+m</kbd>), etc.

I'm thinking to just implement/backport MarGo extensions instead. i.e. You can have a `margo` package in your `GOPATH` that MarGo imports and you can then just plug in the filtering function if desired. I want to move as much of the code and functionality out of GoSublime (Python plugin) so that it can be made available to other editors and non-Go languages. I actually use GoSublime more for non-Go than for Go related programming, but I've always just hacked on extension to make that work.

**Comment by maraino** [comment]
How do you plan to implement the extensions using Go? At compile time? Using sockets or any other method to communicate two binaries ?

Or do you mean have individual binaries (packages) for each one of the methods that MarGo has and then be able to replace for example import_paths with your own implementation ?

**Comment by maraino** [comment]
I've been looking at the history and I think the problem for me appeared with 
https://github.com/DisposaBoy/GoSublime/commit/11bbe2b20ae6ad8c11581b7cb9f8028342ee996e
When the walk through the pkg directory was replaced with the walk through src

**Comment by DisposaBoy** [comment]
I pushed the implementation as package that's compiled into the MarGo binary. 
Yes support for binary packages was (partially) dropped in `r16.04.29-1`.

**Comment by maraino** [comment]
This PR is no longer necessary, long time ago, `goimports` was updated to support something like this with `.goimportsignore`

**Pull request closed without merging**
